apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-statefulset-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: webapp-statefulset
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50