#Assuming mysql is deployed in db namespace. To access the db, the app needs credentials. So, creating the secrets in the same namespace where the app is deployed.
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  labels:
    app: webapp
type: opaque
data:
  db_username: cm9vdA==
  db_password: dDBwLVNlY3JldA==